name = "neko"
main = "src/index.ts"
compatibility_date = "2023-11-21"

[vars]
# cspell: disable
DISCORD_APPLICATION_ID = "1188775821863833641"
DISCORD_APPLICATION_PUBLIC_KEY = "a33e1509bca2910c8ebde944a1ca886dcf11fc8e9051ee2dfdb41cc4ba731d89"
ASSISTANT_ID = "asst_yEYxwYUPMBSbRPms5sYhw4js"
GITHUBCARD_ENDPOINT = "https://opengraph.githubassets.com/githubcard"
# cspell: enable

[[r2_buckets]]
binding = "neko"
bucket_name = "neko"
